version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
      - ./db/test-data.sql:/docker-entrypoint-initdb.d/002_test-data.sql
    networks:
      - storable-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_app
    restart: on-failure
    depends_on:
      - db
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/storable?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/storage
    networks:
      - storable-net

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    networks:
      - storable-net

networks:
  storable-net:
    driver: bridge

volumes:
  db-data:
    driver: local
